api:
    # based off the golang:1.6.1-alpine image

    #Docker hub image
    image: xprincipia/frontend:v3SSL

    # Local host build
    # build:
    #   context: .

    #   dockerfile: dockerfile
    ports:
      - 443:443
      - 80:80
